[package]
name = "avisalogin"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.7.0"
actix-identity = "0.8.0"
actix-session = "0.10.1"
actix-web = "4.9.0"
actix-rt = "2.5.0"
chrono = "0.4.39"
dotenv = "0.15.0"
openidconnect = "4.0.0"
reqwest = "0.12.12"
serde = "1.0.217"
serde_json = "1.0.138"
sqlx = {version = "0.8.3", features = ["postgres", "runtime-tokio", "tls-native-tls"] }
tokio = "1.43.0"
uuid = { version = "1.13.1", features = ["v4"] }
dotenvy = "0.1.0"
jsonwebtoken = "9.3.1"

