[google]
credentials_file = "config/credentials.json"

[database]
host = "env:DATABASE_HOST"
port = "env:DATABASE_PORT"
user = "env:DATABASE_USER"
password = "env:DATABASE_PASSWORD"
dbname = "env:DATABASE_NAME"

